server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /omenaa/ {
        alias /usr/share/nginx/html/omenaa/;
        try_files $uri $uri.html $uri/index.html =404;
    }

    location /omenaa {
        return 301 /omenaa/;
    }

    error_page 404 /omenaa/404.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;
    gzip_min_length 256;
}
