name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build (static export)
        run: npm run build

      - name: Verify output
        run: |
          test -d out || (echo "ERROR: out/ directory not found" && exit 1)
          test -f out/index.html || (echo "ERROR: out/index.html not found" && exit 1)
          echo "Build output OK"
          ls -la out/

  ci-gate:
    needs: build
    runs-on: docker
    steps:
      - run: echo "CI gate passed"

  push-to-external:
    needs: ci-gate
    if: github.event_name == 'push'
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitHub
        run: |
          git remote add external "${{ secrets.EXTERNAL_REPO_URL }}" || git remote set-url external "${{ secrets.EXTERNAL_REPO_URL }}"
          git push external HEAD:main --force
